### ISSUE TITLE
implement secure median

### ISSUE THREAD

**Issue by Ballhausen** [federatedsecure/service-simon#1]
the median is often used e.g. in medical research. it would be good to have a simple implementation for the semi-honest case. 2 parties would be sufficient, N parties would be better.

see e.g.
[https://www.iacr.org/conferences/eurocrypt2004/slides/session1talk3.ppt](https://www.iacr.org/conferences/eurocrypt2004/slides/session1talk3.ppt)
[https://link.springer.com/article/10.1007/s00145-010-9059-9](https://link.springer.com/article/10.1007/s00145-010-9059-9)

**Comment by christiangoelz** [comment]
Thank you for the links. I will take a look at it and get in touch as soon help is needed!

**Comment by federatedsecurecomputing** [comment]
Feature has been implemented.
Pull request has been merged.
